src/app/modules/xm-sidebar/menu/menu.component.html
add the condition for cases when a collapsed menu has empty children
=> fix(app:menu): added condition for empty menu/children.length

scripts/merge-translations.js
this PR solves problem with empty strings in custom translates which were merged and override the core translations with empty strings
=> fix(translates): merging only custom translates with values

src/app/xm-entity/function-list-section/function-list-section.component.html, src/app/xm-entity/function-list-section/function-list-section.component.scss
set auto width for current entity state column to prevent text overflow
=> feat(function-list-section): set auto width for curr state column

src/app/admin-config/specification-mng/specification-mng.component.html, src/app/admin-config/specification-mng/specification-mng.component.ts, src/app/admin/roles-management/roles-management-detail.component.html, src/app/admin/roles-management/roles-management-detail.component.ts, src/app/admin/roles-management/roles-management.component.html, src/app/admin/roles-management/roles-management.component.ts, src/app/admin/roles-matrix/roles-matrix.component.html, src/app/admin/roles-matrix/roles-matrix.component.ts
When flag is TRUE actions (except filters, sort, pagination, etc.) will be blocked for next components:
- specification-mng
- roles-matrix
- roles-management
- roles-management-detail
=> feat(25529): added logic to handle "readOnlyConfig" flag in UI specification

package.json, src/app/application/application.component.html, src/app/ext-commons/ext-common-entity/entity-widget/entity-widget.component.html, src/app/shared/spec/xm-ui-config-model.ts, src/app/xm-entity/entity-detail-fab/entity-detail-fab.component.html, src/app/xm-entity/entity-detail-fab/entity-detail-fab.component.ts, src/app/xm-entity/entity-list-fab/entity-list-fab.component.html, src/app/xm-entity/entity-list-fab/entity-list-fab.component.ts
For UI Config now it's possible to add keys `addButtonPermission` and `editButtonPermission`, with some permission string in value, like:
```
entities: 
- typeKey: ''SOME-ENTITY"
addButtonPermission: "SOME-ENTITY.BTN.ADD"
```
In this example, if `addButtonPermission` exists in entity config, and user haven't specified privilege key, button won't render for this entity.
If entity config doesn't have `addButtonPermission` or `editButtonPermission` key, default logic goes here.
=> feat(list-fab, detail-fab): added check for permission for render add/edit btn for EXACT entity

packages/administration/src/metrics/metrics.component.html
The data-target property of scrollspy in bootstrap versions on or above 4.0.0-alpha and before 4.1.2 are vulnerable to Cross-Site Scripting(XSS) attacks.
=> Fix/remove unused/data params

src/app/modules/xm-sidebar/sidebar.component.ts, src/app/modules/xm-sidebar/xm-sidebar.module.ts, src/app/shared/shared.module.ts, src/app/xm.module.ts
refactor(xm-shared-module): move services to forRoot()
=> refactor(xm-shared-module): move services to forRoot()

package.json, scripts/jsf-ext-importer.js
Fix linter on prebuild  insertBetweenPrefixAndSuffix when generatedModuleImports is empty
=> fix: fix jsf-ext-importer,empty ModuleImports

package.json, packages/components/date/xm-date-range-filter-control.ts
Component options settings have been expanded. An optional firstDayOfWeek field has been added to the IDateOptions interface, which now allows you to set the day from which the week will start. The value of the firstDayOfWeek field must be of type number. Valid value is from 0 to 6. 0: Sunday ~ 6: Saturday
=> feat(xm-date-range-filter-control): set option first day of week

.gitignore, package.json, packages/administration/src/dashboards-config/dashboards.module.ts, packages/administration/src/dashboards-config/widget-edit/schema-editor/schema-editor.component.html, packages/administration/src/dashboards-config/widget-edit/schema-editor/schema-editor.component.ts, packages/administration/src/dashboards-config/widget-edit/widget-edit.component.html, packages/administration/src/dashboards-config/widget-edit/widget-edit.component.spec.ts, packages/administration/src/dashboards-config/widget-edit/widget-edit.component.ts, packages/administration/src/navbar-dashboard-edit-widget/navbar-dashboard-edit-widget.module.ts, packages/cli/src/cli.ts, packages/cli/src/command.ts, packages/cli/src/dynamic-specification/dynamic-specification-command.ts, packages/cli/src/index.ts, src/app/ext/example-webapp-ext/module/example-presentational/example-presentation.module.ts, src/app/ext/example-webapp-ext/module/example-presentational/example-presentational.component.html, src/app/ext/example-webapp-ext/module/example-presentational/example-presentational.component.spec.ts, src/app/ext/example-webapp-ext/module/example-presentational/example-presentational.component.ts, src/app/ext/example-webapp-ext/module/example-presentational/index.ts, src/app/ext/example-webapp-ext/module/example-webapp-ext.module.ts, src/assets/specification/.gitkeep, tsconfig.json
Generates json schema form for ui widget editor, based on field "config" type. Use `xm-ngx dynamic-specification`.
Generated component-spec located at `src/assets/specification/dynamic_components_spec_output.json`.
- IMPORTANT: add `OneOff` and other, implement own jsf;
- add pipeline component-spec validator;
- add switcher between editor and code and remove tab at widget-editor ;
- add webpack plugin to angular and update spec on file change;
- split spec into multiple files;
- build extension specs to extension folder;
- add support for `XmLayout[]` and recursive spec({selector: "sub-component"});
- decorator `[min, max]`;
- description from `tsdoc`;
- generate registry file;
- add `require[]` based on `:?`.
Example of parser for swagger:
// SOURCE: …
=> feat(dynamic): add specification generator

package.json, packages/components/sidebar-right/xm-sidebar-right.module.ts
Calculate right sidebar by page width, not the screen.
Do not propagate event in order to avoid unexpected background text selection.
=> right-sidebar: correct resize width

packages/components/breadcrumb/breadcrumb/xm-breadcrumb.component.html, packages/components/breadcrumb/breadcrumb/xm-breadcrumb.component.scss, packages/components/navbar/back/xm-navbar-arrow-back-widget.component.ts
xm-navbar-arrow-back-widget :   the icon is aligned with the center of the button
xm-breadcrunb: elements are aligned with each other, text size, colors and fat content are corrected
=> fix(xm-breadcrunb, xm-navbar-arrow-back-widget): fix breadcrumbs layout

packages/administration/dashboards-config/dashboard-edit/dashboard-edit.component.ts, packages/administration/dashboards-config/dashboard-editor.service.ts, packages/administration/navbar-dashboard-edit-widget/navbar-dashboard-edit-widget.component.ts, packages/administration/navbar-dashboard-edit-widget/navbar-dashboard-edit-widget.module.ts, packages/dynamic/cell/xm-dynamic-cell.directive.ts
Fixed a defect when the modal for editing the dashboard constantly opened, as if not to click on the edit button again.
How it works now:
-when we press the button edit dashboard, the state of the open modal window is saved in the session store.
- when we press the button to close the modal for editing, this value is removed from the session store.
=> fix(xm-navbar-dashboard-edit-widget): open close state fixed

packages/administration/dashboards-config/dashboard-edit/dashboard-edit.component.ts, packages/administration/dashboards-config/widget-edit/config-editor.component.ts, packages/administration/form-playground/form-playground.component.ts, packages/administration/specification-management/entity-spec-management/entity-spec-management.component.ts, packages/administration/specification-management/private-ui-mng/private-ui-mng.component.ts, packages/administration/specification-management/tenant-mng/tenant-mng.component.ts, packages/administration/specification-management/timeline-mng/timeline-mng.component.ts, packages/administration/specification-management/uaa-login-mng/uaa-login-mng.component.ts, packages/administration/specification-management/uaa-mng/uaa-mng.component.ts, packages/administration/specification-management/ui-mng/ui-mng.component.ts, packages/components/ace-editor/ace-editor-control/xm-ace-editor-control.model.ts, packages/components/ace-editor/ace-editor-control/xm-ace-editor-control.spec.ts, packages/components/ace-editor/ace-editor-control/xm-ace-editor-control.stories.ts, packages/components/ace-editor/ace-editor-control/xm-ace-editor-control.ts, packages/components/ace-editor/index.ts, packages/components/ace-editor/xm-ace-editor.directive.ts, src/polyfills.ts
After YAML support was added, JSON support broke.
- Add fixes to support object-to-JSON conversion
- Rollback JSON formatting
- Replace strings to Enum
- Move Interface and Enum to the model file
=> fix(xm-ace-editor): Fix object to JSON support + formatting

package.json, packages/components/autocomplete-control/autocomplete-control.ts
- Add logic to return empty array for the case when on empty search shouldn't be any results.
=> autocomplete-control: Empty search result case

package.json, packages/components/menu/menu.component.html, packages/components/menu/menu.interface.ts, packages/components/menu/nested-menu.ts
Now all elements in menu behaves as a link, not only nested elements in accordions.
=> fix: Menu parent node as a link

package.json, packages/components/table/table-widget/xm-table-widget.component.html, packages/components/table/table-widget/xm-table-widget.component.scss, packages/components/table/table-widget/xm-table-widget.config.ts, packages/components/table/table-widget/xm-table-widget.stories.ts
- add possibility to hide all header and pagination elements for the tiny table
=> feat: Configure tiny table

package.json, packages/components/breadcrumb/breadcrumb/xm-breadcrumb.component.html, packages/components/breadcrumb/interfaces/xm-breadcrumb.interface.ts, packages/components/breadcrumb/reolvers/xm-breadcrumb-default.resolver.ts
If during navigation your url has queryParams and when you click on previous crumb (to navigate on previous page) you want to keep some of existing queryParams just specify them in dashboard config as array of strings.
For ex:
url: 
https://domain.com/dashboard/parent/child1/child2??callId=123&userId=123-123
breadcrumbs:
`Parent` > `Child1` > `Child2`
So, now you on `Child2` page,  if you want to go back to `Child1` page and keep `userId` param in url, then add to the `Child1` dashboard config:
```json
{
"keepQueryParams": [
"userId"
]
}
```
=> feat: xm-breadcrumbs – keep query params

package.json, packages/components/table/controllers/filters/xm-table-query-params-store.service.ts, packages/components/table/directives/xm-table.directive.ts, packages/components/table/directives/xm-table.model.ts
- add navigation.replaceUrl property to do no push new route to the browser history
- fix bug when pageIndex resets to 0 on every table initialization
=> feat: Add navigation config property and fix bug in xm-table-widget

package.json, packages/components/menu/menu.component.ts, packages/components/menu/menu.service.ts, src/app/layouts/components/layout-wrapper/layout-wrapper.component.ts
- after receiving dashboards check if url path is empty, do navigation to dashboards
- change menu collapse/expand behaviour, now it's hiding immediately when user clicks on Collapse button
- fix issue when user logged out and then login again there was a tiny second when categories were shown from the previous user
=> fix: Menu collapse/expand behaviour, navigation, login/logout categories issue

eslint.config.mjs, package.json, packages/components/ace-editor/ace-editor-control/xm-ace-editor-control.ts, packages/components/ace-editor/xm-ace-editor.directive.ts
- Add possibility to get actual annotations from brace editor
- allow to use `console.error()` in lint config
=> feat: Annotations from brace editor

package.json, packages/components/table/components/xm-table-header.component.ts
- add possibility to add icon in table header
- refactor structure directives to the control flow
- refactor css syntax to the scss
In case you need to specify another styles for the icon use you theme file to override the styles.
=> Add icon and small refactoring for the table header

package.json, packages/components/control-error/control-errors.directive.ts
In case you need to pass you custom error message translation, you can use the `xmControlErrorsExtraErrorTranslations` input:
```html
<mat-error *xmControlErrors="inputControl.errors; extraErrorTranslations: extraErrorTranslations; message as message;">
{{ message }}
</mat-error>
```
where extraErrorTranslations:
```ts
public extraErrorTranslations: XmControlErrorsTranslates = {
unique: marker('ext.translation.key.to.the.unique.error.message'),
};
```
=> Feat: Add extra error cases to the *xmControlErrors directive

package.json, packages/administration/client-management/client-management.component.ts
- make dialog width bigger to make it possible to display long scope names correctly
=> fix: Long scope name

package.json, packages/administration/dashboards-config/components/dashboards-transfer/dashboards-transfer.component.ts, packages/administration/dashboards-config/components/dashboards-transfer/services/dashboards-transfer-api.service.ts, packages/administration/dashboards-config/components/dashboards-transfer/services/roles-state.service.ts
Add the ability to create roles in the target environment based on the corresponding local environment role, if a role with the same typeKey does not exist in the target environment.
=> feat(role-transfer): Add ability to create roles on target env if not exist

package.json, packages/dashboard/src/components/dashboard/dashboard.component.html, packages/dashboard/src/components/dashboard/dashboard.component.ts
With logout for 0.5 seconds we have block of our dashboard. 
To fix it i`ve added session and logout event subscription for validate block
=> Added dashboard configuration for not showing if session is not active
