src/docker/Dockerfile
src/docker/entrypoint.sh
src/docker/nginx.tmpl

Be endpoints

---

src/app/shared/jsf-extention/widgets/ext-select/ext-select.component.html
src/app/shared/jsf-extention/widgets/ext-select/ext-select.component.ts

Feature add jsf watch field

---

src/app/ext-commons/ext-common-entity/entity-fab-actions/entity-fab-actions.component.ts
src/app/xm-entity/entity-detail-dialog/entity-detail-dialog.component.ts

Added ability to redirect to created entity application/dashboard after successful creation.

xm-widget-entity-fab-actions.

---

package.json
src/app/shared/helpers/file-download-helper.ts
src/app/xm-entity/attachment-card/attachment-card.component.ts
src/app/xm-entity/shared/attachment.model.ts

This feature allows to download attachment from 3rd party storage

Added attachment by url download

---

src/app/xm-entity/entity-detail-fab/entity-detail-fab.component.html
src/app/xm-entity/entity-detail-fab/entity-detail-fab.component.ts

Added ability to control displaying fab options links buttons via permission

Entity-detail-fab. Added permission check for link fab option button

---

proxy.conf.js

Important change for [this ](https://github.com/xm-online/xm-ms-otp/pull/25) PR

otp login feature: add /otp to proxy content

---

src/app/ext-commons/ext-common-entity/entity-widget/entity-widget.component.html
src/app/ext-commons/ext-common-entity/entity-widget/entity-widget.component.ts
src/app/shared/language/language.helper.ts
src/app/xm-dashboard/shared/dashboard-wrapper.service.ts
src/app/xm-entity/attachment-list/attachment-list-base.component.ts
src/app/xm-entity/calendar-card/calendar-card.component.ts
src/app/xm-entity/rating-list-section/rating-list-section.component.ts
src/app/xm-entity/shared/xm-entity-spec-wrapper.service.ts
src/app/xm-entity/tag-list-section/tag-list-section.component.ts

1. removed backend calls, is spec for feature is not provided
2. added debug information
3. this is pre-stage to reactive entity-card refactoring
Details
https://tracker.jbs.com.ua/issues/20034

EntityCard call optimisation (no calls if spec is not provided)

---

src/app/shared/auth/auth-jwt.service.ts
src/app/shared/helpers/custom-uri-encoder.ts

Adding custom CustomUriEncoder helper to use with default httpParams.

adding custom encoding class to use with httParams

---

config.angular.json
scripts/manage-exts.js

set SCSS as default
remove e2e config

refactor: replace md-pro-angular-cli with xm-webapp

---

package.json

1. `npm run build`
2. `npm run report:bundle`
3. Navigate to http://127.0.0.1:8888

feat(package): add webpack-bundle-analyzer

---

src/app/xm-dashboard/dashboard/dashboard.component.html
src/app/xm-dashboard/dashboard/dashboard.component.ts

Signed-off-by: Ihor Shkurko <ishkurko@gmail.com>

Dashboard deep layout

---

src/app/shared/helpers/xm-entity-icon.pipe.ts
src/app/shared/shared.module.ts
src/app/xm-entity/link-detail-dialog/link-detail-dialog.component.html
src/app/xm-entity/link-detail-dialog/link-detail-search-section.component.html
src/app/xm-entity/link-detail-dialog/link-detail-search-section.component.ts

for the entity's links type "SEARCH" in the list of entities selection
AS IS: the icons shown in the list refers to the icon of the link type or parent entity type (PRICES)
TO BE: icons shown in the list should be taken from the linked entity full type (PRICES.USAGE)

Link-detail-search-section. Replaced link spec icon with entity spec icon

---

src/app/application/application.component.ts
src/app/layouts/navbar/navbar.component.ts

When there is no config for search, for some reason console throws error in tenant compass

Navbar. Search. Fixed wrong method behaviour

---

src/assets/scss/theme-override.scss

https://tracker.jbs.com.ua/issues/22156

 Fix bug with menu overlaps

---

.gitignore
src/app/application/application.component.ts
src/app/ext-commons/ext-common-entity/entity-list-widget/entity-list-widget.component.ts
src/app/xm-entity/entity-list-card/entity-list-card.component.html

Idea is to use _hideDelete_ fetaure to hide _delete_ button on tenant list

Feature/hide delete for RESOURCE.TENANT with default hide options

---

src/app/ext-commons/ext-common/md-widget/md-widget.component.ts

https://tracker.jbs.com.ua/issues/22029

Fix md-widget save bug

---

config.angular.json
src/app/admin/roles-management/roles-management-delete-dialog.component.ts
src/app/admin/roles-management/roles-management-dialog.component.ts
src/app/admin/roles-matrix/roles-matrix.component.html
src/app/admin/roles-matrix/roles-matrix.component.ts
src/app/ext-commons/ext-common-entity/tasks-widget/tasks-widget.component.ts
src/app/layouts/sidebar/sidebar.component.ts
src/app/shared/auth/has-any-authority.directive.ts
src/app/shared/helpers/entity-list-helper.spec.ts
src/app/shared/jsf-extention/jsf-attributes-helper.ts
src/app/shared/jsf-extention/widgets/current-location/current-location-options.model.ts
src/app/shared/jsf-extention/widgets/ext-autocomplete/ext-autocomplete-service.ts
src/app/shared/jsf-extention/widgets/ext-autocomplete/ext-autocomplete.component.ts
src/app/shared/jsf-extention/widgets/ext-select/ext-select-options.model.ts
src/app/shared/jsf-extention/widgets/ext-select/ext-select-service.ts
src/app/shared/jsf-extention/widgets/ext-textarea/ext-textarea-options.model.ts
src/app/shared/jsf-extention/widgets/validation-component/validation-component.model.ts
src/app/shared/privilege/privilege.directive.ts
src/app/shared/role/permission.model.ts
src/app/shared/role/role.model.ts
src/app/shared/social/social.component.ts
src/app/shared/spec/xm-config.service.ts
src/app/shared/user/login/user-login-form.component.ts
src/app/shared/user/login/user-login.model.ts
src/app/xm-dashboard/dashboard/dashboard.component.ts
src/app/xm-entity/attachment-list/attachment-list-simplified.component.ts
src/app/xm-entity/entity-list-card/entity-list-card-options.model.ts
tslint.json

Replace classes by interfaces:
```
class CurrentLocationOptions 
class ExtSelectOptions 
class ExtTextareaOptions 
class CurrentLocationOptions
class Permission
class Role
class RoleMatrix
class RoleMatrixPermission
class UserLogin
class EntityListCardOptions
class EntityOptions
class FieldOptions
class ActionOptions
class ActionsOptions
class FilterOptions
```
refactor `sidebar.component`.

refactor: tslint

---

.travis.yml
package.json

Add `npm run lint` to the `.travis.yml` file.

build: provide lint script

---

src/app/xm-routing.module.ts
src/tsconfig.app.json
src/tsconfig.spec.json

feat(xm-routing): import lazy modules

---

src/app/ext-commons/ext-common-entity/entity-widget/entity-widget.component.ts

added possibility for setup detailLayoutType based on settings-public.yml

add config defaultDetailLayoutType

---

src/app/modules/xm-sidebar/menu/menu-models.ts
src/app/modules/xm-sidebar/user/user.component.html
src/app/modules/xm-sidebar/user/user.component.ts

- it was deprecated by *permitted directive, and the suggestion is to show for * users logout control

Refactor logout accessibility

---

src/app/admin/user-management/user-management-detail.component.ts

adding service provider

---

src/app/admin/gateway/gateway.component.html
src/app/admin/metrics/metrics.component.html
src/app/admin/user-management/user-management.component.html

fix: mat-fab color #231

---

package.json
src/app/application/application.module.ts
src/app/modules/components/xm-rating/index.ts
src/app/xm-entity/xm-entity.module.ts

ngx-raing was archived and isn't compatible with angular 9

feat: replace ngx-rating with custom

---

src/app/admin/admin.service.ts
src/app/admin/client-management/client-management.component.html
src/app/admin/roles-management/roles-management-detail.component.html
src/app/admin/roles-management/roles-management-detail.component.ts
src/app/admin/roles-management/roles-management.component.html
src/app/admin/roles-management/roles-management.component.ts
src/app/admin/roles-matrix/roles-matrix.component.html
src/app/admin/roles-matrix/roles-matrix.component.ts
src/app/admin/user-management/user-management.component.html

https://github.com/xm-online/xm-online/issues/133

fix: incorrect page assign #133

---

src/app/modules/xm-core/src/xm-event-manager.service.ts

chore(xm-event-manger): rename cache to dispatcher

---

src/app/layouts/navbar/feedback/feedback.component.ts
src/app/modules/xm-core/src/config/xm-private-ui-config.service.ts
src/app/modules/xm-core/src/config/xm-public-ui-config.service.ts
src/app/modules/xm-core/src/config/xm-ui-config.service.ts
src/app/modules/xm-ribbon/xm-ribbon.component.ts
src/app/modules/xm-sidebar/logo/logo.component.ts

chore(xm-ui-config): rename cache$ to config$()

---

src/app/shared/privilege/xm-permission.service.ts

chore(xm-permission): add empty value

---

packages/components/src/pagination/index.ts
packages/components/src/pagination/pagination.constants.ts
src/app/admin-config/base-admin-config-list.component.ts
src/app/admin-config/dashboard-mng/dashboard-list-card/dashboard-list-card.component.ts
src/app/admin/admin.service.ts
src/app/admin/roles-management/roles-management-detail.component.ts
src/app/admin/roles-management/roles-management.component.ts
src/app/admin/roles-matrix/roles-matrix.component.ts
src/app/shared/constants/pagination.constants.ts
src/app/shared/index.ts

chore(ITEMS_PER_PAGE): move to packages/

---

src/app/shared/language/modules-language.helper.ts

fix(module-language.helper): restore

---

packages/administration/src/high-level-architecture-widget/high-level-architecture-widget.component.html
packages/administration/src/high-level-architecture-widget/high-level-architecture-widget.component.spec.ts
packages/administration/src/high-level-architecture-widget/high-level-architecture-widget.component.ts
packages/administration/src/high-level-architecture-widget/index.ts
src/app/admin/admin.registry.ts

feat(high-level-architecture-widget): move tp /packages

---

src/app/modules/xm-sidebar/menu/menu.component.ts

we should change the way of the sidebar menu generation

chore(menu): hotfix sidebar madness

---

.travis.yml
deploy/docker-compose.yml
package.json
src/docker/Dockerfile

add docker compose

---

src/app/xm-entity/calendar-event-dialog/calendar-event-dialog.component.ts
src/app/xm-entity/shared/event.model.ts

fix(develop): reworked calendar events creation
(cherry picked from commit 19590cfa0a40a8938497b7eba1adc856279254ac)

Calendar. Reworked event creating, changed model

---

src/app/xm-entity/attachment-card/attachment-card.component.html
src/app/xm-entity/attachment-card/attachment-card.component.scss
src/app/xm-entity/attachment-card/attachment-card.component.ts

Download attachment on preview click feat from master

Backport 942d136f5a3a0ae09dc69d50089e7851ff8abb29 from master

---

src/app/ext-commons/ext-common/md-widget/md-widget.component.html
src/app/ext-commons/ext-common/md-widget/md-widget.component.ts
src/assets/scss/theme-override.scss

Fixing editor styles.
Adding permission check for edit controls.
Fix preview toggle only if needed.

MD editor fixing

---

src/app/xm-dashboard/shared/dashboard-wrapper.service.ts

fix(dashboard): fix empty dashboard after login

---

packages/administration/src/specification-management/entity-spec-editor/entity-spec-yaml.service.ts

Improve spec to yaml serialisation.

feat(spec): improve yaml serialization

---

packages/administration/src/specification-management/entity-spec-editor/entity-spec-editor.component.ts

Signed-off-by: Ihor Shkurko <ishkurko@gmail.com>

fix(spec): fix change data and form specs

---

packages/components/src/animations/route-change-animation/route-change-animation.directive.ts

fix fixed position inside translateY

fix(route-change-animation): remove player after animation complete

---

package.json

this PR fix broken sidebar, with uses older jQuery

fix(sidebar): fixing sidebar

---

src/app/home/home.component.ts
src/app/layouts/navbar/xm-navbar.module.ts
src/app/shared/components/privacy-and-terms-dialog/privacy-and-terms-dialog.component.html
src/app/shared/components/privacy-and-terms-dialog/privacy-and-terms-dialog.component.scss
src/app/shared/components/privacy-and-terms-dialog/privacy-and-terms-dialog.component.ts
src/app/shared/login/login.component.ts

this PR fixes privacy and policy in develop

fix(login-terms-and-conditions): fixing terms in develop

---

packages/components/src/xm-notifications/notifications/notifications.component.html
packages/components/src/xm-notifications/notifications/notifications.component.scss
packages/components/src/xm-notifications/notifications/notifications.component.ts
packages/components/src/xm-notifications/xm-notifications.module.ts
src/app/layouts/navbar/navbar.component.scss

this PR solves problems in notification module in develop

fix(notifications): refactor using native mat-menu

---

src/app/application/application.component.ts
src/app/layouts/navbar/navbar.component.html
src/app/layouts/navbar/xm-navbar-input-search.component.scss
src/app/layouts/navbar/xm-navbar-input-search.component.ts
src/app/layouts/navbar/xm-navbar.module.ts
src/app/xm-entity/entity-list-card/entity-list/entity-list.component.ts

this PR fixes broken search global in develop

fix(search-glodal): fixing broken search

---

src/app/shared/jsf-extention/widgets/ext-select/ext-select-options.model.ts
src/app/shared/jsf-extention/widgets/ext-select/ext-select.component.html
src/app/shared/jsf-extention/widgets/ext-select/ext-select.component.ts

this PR adds feature from master for ext selext jsf widget

fix(ext-select): adding ext select deep link support from master

---

src/app/xm-entity/link-list-card/link-list-card.component.html
src/app/xm-entity/link-list-card/link-list-card.component.ts

this PR fixes broken back-links in develop

fix(back-links): fixing broken back-links

---

packages/components/src/menu/_menu-theme.scss
packages/components/src/sidebar-user/sidebar-user.component.html
src/app/xm-dashboard/shared/dashboard-wrapper.service.ts
src/app/xm-dashboard/shared/dashboard.service.ts

fix sidebar show logout by default

fix(dashboards): add catchError

---

src/app/xm-entity/entity-list-card/entity-list/entity-list.component.ts

this PR solves problem with update of list after modification events

fix(entity-list): fixing update list on modufucations

---

package.json
src/app/shared/login/login.component.ts

this PR solves issue on redirect with query params after login

fix(login): redirect with params

---

src/app/mat.module.ts
src/app/xm-entity/entity-list-card/entity-list-card.component.html
src/app/xm-entity/entity-list-card/entity-list/entity-list.component.html
src/app/xm-entity/entity-list-card/entity-list/entity-list.component.ts
src/app/xm.constants.ts
src/app/xm.mat-paginator-int.ts

this PR solved mat-paginator in entity list

fix(entity-list): using mat-paginator, providing translations

---

src/app/xm-entity/entity-list-card/entity-list/entity-list.component.html
src/app/xm-entity/entity-list-card/entity-list/entity-list.component.ts

this PR fix sort considering sortable prop

fix(entity-list): sort considering sortable prop

---

src/app/shared/jsf-extention/widgets/multilingual-input/multilingual-input.component.ts

this PR fixes multy lang input widget

fix(jsf-widgets): fix multi-lang input widget

---

packages/administration/src/roles-management-detail/roles-management-detail.component.html
packages/administration/src/roles-management-detail/roles-management-detail.component.ts
packages/administration/src/roles-management-detail/roles-management-detail.module.ts

this PR solves issue with old roles edit implementetion in develop

refactor(roles-edit): moving to mat-table, methods rewrite, cleanup

---

packages/components/src/xm-notifications/notifications/notifications.component.html
packages/components/src/xm-notifications/notifications/notifications.component.scss
packages/components/src/xm-notifications/notifications/notifications.component.ts
src/app/layouts/navbar/navbar.component.html
src/app/layouts/navbar/navbar.component.ts

this PR solves init problem, adds default styling

fix(notifications): fix-init, styling

---

src/app/ext-commons/ext-common-entity/stats-widget/stats-widget.component.html
src/app/ext-commons/ext-common-entity/stats-widget/stats-widget.component.scss

this PR fixes styles in stats widget in develop

fix(stats-widget): fixing layout and styles

---

src/app/xm-timeline/timeline/timeline.component.html
src/app/xm-timeline/timeline/timeline.component.scss

Fixes styling for history timline in develop

fix(timeline): fixing styles in timeline

---

src/app/xm-entity/avatar-dialog/avatar-dialog.component.html
src/app/xm-entity/avatar-dialog/avatar-dialog.component.scss
src/app/xm-entity/entity-card-compact/entity-card-compact.component.html
src/app/xm-entity/entity-card-compact/entity-card-compact.component.scss
src/app/xm-entity/entity-card/entity-card.component.html
src/app/xm-entity/entity-card/entity-card.component.scss
src/app/xm-entity/entity-card/entity-card.component.ts

this PR fixes styles for avatar details buttons and preview

fix(avatar-dialog): fix file button and preview styles

---

package.json
src/app/xm-entity/link-detail-dialog/link-detail-search-section.component.html
src/app/xm-entity/link-detail-dialog/link-detail-search-section.component.ts
src/app/xm-entity/shared/link.service.ts

Integrating new search api, using debounce input instead of change

Integrating new search api, using debounce input instead of change

---

package-lock.json
package.json
packages/administration/src/form-playground/form-playground.component.html
src/app/shared/jsf-extention/widgets/ext-multi-select/ext-multi-select.component.html
src/app/shared/jsf-extention/widgets/ext-query-select/ext-query-select.component.html
src/app/shared/jsf-extention/widgets/ext-select/ext-select.component.html
src/app/xm-entity/location-detail-dialog/location-detail-dialog.component.html
src/app/xm-entity/states-management-dialog/states-management-dialog.component.html
src/i18n/en/core.json
src/i18n/ru/core.json
src/i18n/uk/core.json

ngx-mat-select-search package updated to fix issue when placeholderLabel not showing in latest Angular version.
Setted i18n default value of placeholderLabel. All usages inside mat-select wrapped by mat-option due to package breaking change in version 3.0.0

Updating ngx-mat-select-search package to v3.1.0

---

package.json
src/app/layouts/main/main.component.ts
src/app/xm-entity/entity-card/entity-card.component.html
src/app/xm-entity/entity-card/entity-card.component.ts
src/app/xm.constants.ts

This MR adds tenant reload configuration button on Applciation card.

Add reload button on Application card

---

package.json
src/app/shared/spec/xm-ui-config-model.ts
src/app/xm-entity/calendar-card/calendar-card.component.ts
src/app/xm-entity/function-call-dialog/function-call-dialog.component.ts
src/app/xm-entity/link-list-card/link-list-card.component.html
src/app/xm-entity/link-list-card/link-list-card.component.ts

- link list: _optional_ hide card options if list is empty
- link list: _optional_ no items text message if list is empty
- calendar: BE items fetch size configuration

UI configuration features

---

src/assets/js/old-browsers/index.js
src/assets/scss/xm-styles.scss
src/index.html

This script designed for compatibility with old browsers and checks current userAgent version, compares it with most recent browsers that support Angular, and shows popup when userAgent version less than recommended.
Part that checks current userAgent version was tested with many of the most popular browsers.
Creation of popup markup and other actions works only if old browser detected.

feat(25488): Message to prevent use of the old browsers

---

src/assets/js/old-browsers/index.js
src/index.html

This script designed for compatibility with old browsers and checks current userAgent version, compares it with most recent browsers that support Angular, and shows popup when userAgent version less than recommended.
Part that checks current userAgent version was tested with many of the most popular browsers.
Creation of popup markup and other actions works only if old browser detected.

feat(25488): making backport of pr #799 from master

---

packages/dashboards/import.js
packages/dashboards/source/dashboards.json

To apply default config:
```
node import.js --xmurl="__API_URL__" --xmgrant="grant_type=password&username=xm&password=P@ssw0rd" --xmauth="Basic aW50ZXJuYWw6aW50ZXJuYWw=" --target="source/dashboards.json"
```
**WARNING: All previous configs will be deleted**

feat(dashboards): add dashboards.json #628

---

src/app/xm-entity/entity-detail-dialog/entity-detail-dialog.component.ts

fix(entity-details): fix filtering spec backport

---

package.json

Get versioning for docker builds tag "project version"

get_versioning

---

src/app/xm-entity/xm-mat-card/xm-mat-card.component.html
src/app/xm-entity/xm-mat-card/xm-mat-card.component.ts

add functionality to show edit buttons by permission

feat(mat-card): add edit by permission

---

packages/administration/src/gateway/gateway.component.html
packages/administration/src/style-guide/style-guide.component.html

chore(links): add noopener

---

src/app/layouts/profiles/page-ribbon.css

https://caniuse.com/?search=transform
Application maintain browsers that implement full suport for CSS3 2D Transforms

feat(ribone-styles): remove unused prefixes

---

src/app/ext-commons/ext-common/weather-widget/weather-widget.component.scss

fix misprint 
Replace unknown list-height to line-height

fix(weather-widget): replace list-height to line-height.

---

src/app/xm-entity/attachment-detail-dialog/attachment-detail-dialog.component.ts

Add dran&drop  AttachmentDetailDialogComponent

Feature dnd

---

packages/logger/src/xm-console.logger.ts
packages/logger/src/xm-logger-watcher.service.ts
packages/logger/src/xm-logger.module.ts
packages/logger/src/xm-logger.service.ts
src/app/xm-entity/xm-mat-card/xm-mat-card.component.ts
src/app/xm.module.ts

Release branch develop into branch release

---

packages/components/date/xm-datetime-control.ts

- simplifies existing code
- adds official support of string values
- adds an ability to provide default value to the control.

feat(XmDatetimeControl): General improvements

---

packages/components/mat-fab/mat-fab-widget.component.html
packages/components/mat-fab/mat-fab-widget.component.ts

feat(fab-button): route with query params

---

packages/components/breadcrumb/breadcrumb/xm-breadcrumb.component.html
packages/components/breadcrumb/breadcrumb/xm-breadcrumb.component.scss
packages/components/breadcrumb/stores/xm-breadcrumb.store.ts
packages/components/navbar/back/xm-navbar-arrow-back-widget.component.ts

fix(breadcrumb): fix first empty load

---

packages/components/edit-buttons/edit-widget-buttons.component.html
src/app/xm-entity/xm-mat-card/xm-mat-card.component.html
src/app/xm-entity/xm-mat-card/xm-mat-card.component.ts

feat(xm-mat-card): add data-qa

feat(xm-mat-card): add data-qa

---

packages/administration/src/roles-management-detail/condition-dashboard-dialog/condition-dashboard-dialog.component.spec.ts
packages/components/link/link-button/xm-link-button.component.spec.ts
packages/components/sidebar-user/sidebar-user.component.spec.ts
packages/components/sidebar-user/sidebar-user.component.ts
packages/components/sidebar-user/user-widget.base.ts
packages/dashboard/src/guards/dashboard.guard.spec.ts
src/app/account/idp-callback/idp-callback.component.spec.ts

test: update mock usage
fix child extends parent error (undefined of the any injected class) at SidebarComponent

test: update mock usage

---

src/app/shared/jsf-extention/widgets/ext-multi-select/ext-multi-select.component.ts
src/app/shared/jsf-extention/widgets/ext-select/base-ext-select.component.ts
src/app/shared/jsf-extention/widgets/ext-select/ext-select-service.ts
src/app/shared/jsf-extention/widgets/ext-select/ext-select.component.ts

Support URL relations for ext-multi-select, just bsckport of #962

Backport of PR #962 from master to develop

---

packages/components/feedback/feedback.component.ts
packages/components/feedback/feedback.module.ts
packages/components/feedback/index.ts
src/i18n/en/core.json

reafactor(i18n): fix feedback

---

packages/shared/operators/index.ts
packages/shared/operators/src/remove-empty-deep.spec.ts
packages/shared/operators/src/remove-empty-deep.ts
packages/shared/operators/src/transform-by-map.spec.ts
packages/shared/operators/src/transform-by-map.ts

fix(transform): add empty string check

---

packages/components/logo/logo.component.ts
src/app/layouts/navbar/navbar.component.ts

feat(sidebar): add class to host

---

package.json
packages/components/logo/image-logo/image-logo.component.html
packages/components/logo/image-logo/image-logo.component.spec.ts
packages/components/logo/image-logo/image-logo.component.ts
packages/components/logo/image-logo/image-logo.module.ts
packages/components/logo/index.ts
packages/shared/operators/index.ts
packages/shared/operators/src/random-int.ts
src/registries/xm.registry.ts

Widget can be used to display image in sidebar logo

feat(logo): add component to display logo as image

---

package.json
packages/administration/src/docs/docs.component.ts

Add microservice name from config to request url pathname

feat(docs-component): modify url in swagger request

---

src/app/xm.module.ts

Add NgxMaskModule.forRoot() at main module. Fix issues with lazy modules(modal) and wrong InjectionToken

feat(main): add global input mask for input lazy components

---

package.json
packages/components/radio-group/radio-group-control.component.ts
packages/confirm-dialog/src/confirm-dialog.component.html
packages/confirm-dialog/src/confirm-dialog.component.ts
packages/confirm-dialog/src/confirm-dialog.interface.ts
packages/confirm-dialog/src/confirm-dialog.module.ts

add permission to dialog control item and radio item

feat(dialog-radio-permission): permission to dialog control and radio

---

package.json
src/app/shared/jsf-extention/widgets/ext-md-editor/ext-md-editor.component.html

feat: adding save btn for jsf edit widget

---

package.json
packages/json-schema-form/components/flex-layout-root.component.ts
packages/json-schema-form/components/flex-layout-section.component.ts
packages/json-schema-form/components/material-design-framework.component.ts
packages/json-schema-form/core/material-design-framework.ts
packages/json-schema-form/core/xm-json-schema-form.module.ts
packages/json-schema-form/core/xm-json-schema-form.service.ts

Angular json form rendering input elements and many of them has text area. This pr add drag handle instead whole area 
Maybe there is a better solution

feat(ajsf-handle-drag): add custom handle for drag elements

---

package.json
packages/administration/src/roles-management-detail/roles-management-detail.component.html

In order to avoid request duplication we need to disable 'save' button while request performs

feat(roles-managment): disable save button while loading

---

package.json
packages/components/menu/_menu-theme.scss
packages/components/menu/menu.component.html
packages/components/menu/menu.component.ts
packages/components/menu/xm-menu.module.ts

Separate link click on two parts: link and icon

feat(menu-separate-click-event): separate link click: link and icon

---

package.json
packages/components/text/text-range-control/xm-text-range-control.component.ts

fix(xm-text-range-control): fixed mat-hint styles

---

package.json
packages/components/array-control/array-control/xm-array-control.component.ts

fix(xm-array-control): failed test build fixed

---

package.json
packages/dynamic/src/presentation/xm-dynamic-presentation-base.directive.ts
packages/dynamic/src/presentation/xm-dynamic-presentation-layout.component.ts
packages/dynamic/src/presentation/xm-dynamic-presentation.directive.ts

Render dynamic widget config with input name `config`

feat(presentation-options-and-config): render dynamic widget with config

---

package.json
packages/components/menu/menu.component.ts
packages/core/src/xm-public-ui-config-model.ts

Fixing private config for sidebar layout

fix: hideAdminConsole from private configs

---

package.json
packages/confirm-dialog/src/confirm-dialog.component.html
packages/confirm-dialog/src/confirm-dialog.interface.ts
packages/confirm-dialog/src/confirm-dialog.service.ts

added translate options to buttons

feat(confirm-dialog): added translate options to buttons

---

package.json
packages/entity/src/xm-mat-card/xm-mat-card.component.html
packages/timeline/timeline-list/timeline-card/timeline-card.component.html
packages/timeline/timeline-list/timeline-card/timeline-card.component.scss
packages/timeline/timeline-list/timeline-list.component.html
packages/timeline/timeline-list/timeline-list.component.scss

feat(card): add scroll, restyle

---

package.json
packages/components/date/date.control.scss
packages/components/date/xm-date-range-filter-control.ts

change input placeholder to mat-label

fix(xm-date-range-filter-control): change input placeholder to mat-label

---

package.json
packages/components/number-control/index.ts
packages/components/number-control/xm-number-control.module.ts
packages/components/number-control/xm-number-control.ts
packages/components/number-control/xm-number.directive.ts

feat(components/number): add number directive

---

config.angular.json
package.json

fix(core): fix angular editor

---

package.json
packages/dashboards/export.js
packages/dashboards/import.js
packages/dashboards/package.json

feat(dashboards): change to bulk api

---

.travis.yml
package.json
packages/components/date/xm-date-control.ts

xm-dete-control: 
- added an option that prevents you from selecting any date in the past

feat(xm-date-comtrol): add date now option

---

package.json
packages/administration/src/dashboards-config/dashboards-list/dashboards-list.component.ts

feat(dashboards): add sort by order index

---

.travis.yml
deploy/deploy-webapp.sh
package.json
packages/dashboards/package.json

refactor(ci): move build to deploy

---

.travis.yml
deploy/deploy-webapp.sh
package.json
packages/cli/package.json
packages/components/package.json

feat (ci): add skip_cleanup: true

---

README.md
package.json

feat(README): add travis status

---

package.json
packages/administration/src/dashboards-config/widget-edit/schema-editor/schema-formly-ext.ts
packages/components/text-search-pattern/text-search-pattern-control.component.ts
src/app/xm.module.ts

фикс для аот для формли приьрав інкапсуляцію addWidgetEditSchema

refactor(xm.module): fix aot build

---

README.md

Add packages development guide to readme

feat(readme): add packages description

---

src/app/ext-commons/ext-common/sign-in-up-v2-widget/login-v2/login-v2.component.ts
src/app/ext-commons/ext-common/sign-in-up-v2-widget/sign-in-up.service.ts

Fix localstorage/sessionstorage remember me functional on login page

Fix/ remember me state

---

packages/components/letter-control/letter-control.ts

add posibility to get OTP code from SMS and autofill

feat(core): OTP_SMS add posibility to get code from SMS and autofill

---

package.json
packages/components/table/components/xm-table-filter-chips.component.ts

update imports use package instead of file

fix(table): update imports

---

package.json
packages/translation/index.ts
packages/translation/src/pipes/translate.pipe.ts

add xmTranslate pipe
depricate translate

feat(translation): add xmTranslatePipe

---

package.json
packages/components/edit-buttons/edit-widget-buttons.module.ts
packages/components/registry/xm.registry.ts
packages/components/text/text-control/xm-text-control.ts
packages/components/text/text-range-control/xm-text-range-control.component.ts

Add edit widget to registry
Text control remove required by default

chore(edit-widget): add edit widget to registry

---

package.json
packages/components/layout/card/card-layout.model.ts
packages/components/layout/data/data-layout.model.ts
packages/components/layout/editable/editable-layout.model.ts
packages/components/layout/expandable/expandable-layout.model.ts
packages/components/layout/form/form-layout.model.ts
packages/components/layout/list/list-layout.model.ts
packages/core/dashboard/models/dashboard.model.ts
packages/dashboard/src/components/dashboard/dashboard.component.html
packages/dynamic/cell/xm-dynamic-cell.directive.ts
packages/dynamic/control/xm-dynamic-control.directive.ts
packages/dynamic/presentation/xm-dynamic-presentation-base.directive.ts
packages/dynamic/presentation/xm-dynamic-presentation.directive.ts
packages/dynamic/src/dynamic.injectors.ts
packages/dynamic/src/services/xm-dynamic-controller-injector-factory.service.ts
packages/dynamic/widget/xm-dynamic-widget.directive.ts
packages/json-schema-form/components/ext-select/ext-select.component.ts

Add an ability to retrieve component config by InjectionToken.
Add an ability to define controllers on widget level.

Pass dynamic controllers to widget

---

packages/dashboard/navbar-user-widget/navbar-user-widget.component.html
packages/dashboard/navbar-user-widget/navbar-user-widget.component.scss
packages/dashboard/navbar-user-widget/navbar-user-widget.model.ts
packages/dashboard/sidebar-user/user-widget.base.ts

change default navbar user menu /remove settings link

fix(core):update default menu list

---

package.json
packages/dashboard/navbar-user-widget/navbar-user-widget.component.html
packages/dashboard/navbar-user-widget/navbar-user-widget.component.scss
packages/dashboard/navbar-user-widget/navbar-user-widget.model.ts
packages/dashboard/sidebar-user/sidebar-user-subtitle.ts

fix(core): add posibility to change primary btn url-change

---

package.json
packages/dashboard/navbar-user-widget/navbar-user-widget.component.html

add posibility to hide edit avatar btn

fix(core): navbar user hide edit avatar btn

---

package.json
packages/dashboard/navbar-user-widget/navbar-user-widget.component.html

remove prevent stopPropagation() to close after click

fix(core): user-nav bar settings btn close after click

---

package.json
packages/components/table/components/xm-table-filter-button.component.ts
packages/components/table/components/xm-table-filter-chips.component.ts
packages/components/table/controllers/filters/xm-table-filter-controller.service.ts
packages/components/table/table-widget/xm-table-widget.component.html

Keep fixed filters on both view
Add padding if pagination is missing

chore(xm-table): some fixes

---

package.json
packages/components/table/directives/xm-table.directive.ts
packages/entity/src/entity-list-card/entity-table/entity-table.component.ts

Use required defaults: sortBy, sortOrder

fix(table): sortby, sortorder

---

package.json
packages/components/icon/xm-icon.component.ts
packages/components/icon/xm-icon.stories.ts
packages/components/registry/xm.registry.ts

simplest icon component to draw a static icon.
It also could have tooltip as well as enum-icon component

feat(icon): new component

---

packages/components/table/cells/table-array/table-array.component.ts

add option to display list as wrapped row

feat(core): add possibility to show data as wrapped lines

---

package.json
packages/account/account.module.ts
packages/account/password-reset/finish/password-reset-finish.component.html
packages/account/password-reset/finish/password-reset-finish.component.ts
packages/account/password/password.component.html
packages/account/password/password.component.ts
packages/account/password/password.module.ts
packages/account/user-settings-widget/xm-user-settings-widget.component.spec.ts
packages/account/user-settings-widget/xm-user-settings-widget.component.ts
packages/components/password-policies/index.ts
packages/components/password-policies/ng-package.json
packages/components/password-policies/password-policies.component.html
packages/components/password-policies/password-policies.component.scss
packages/components/password-policies/password-policies.component.ts
packages/components/password-policies/password-policy.model.ts
packages/components/password-strength-bar/password-strength-bar.component.ts
packages/components/register/register.component.html
packages/components/register/register.component.ts
packages/core/config/testing/index.ts
packages/core/config/testing/mock-config.service.ts
packages/shared/src/shared.module.ts
src/app/xm.constants.ts
src/i18n/de/core.json
src/i18n/en/core.json
src/i18n/it/core.json
src/i18n/ru/core.json
src/i18n/uk/core.json

Porting password policies from master

feat: porting feature password policies from master

---

package.json
packages/components/carousel/carousel.component.stories.ts
packages/components/carousel/carousel.component.ts
packages/components/carousel/carousel.directive.ts
packages/components/carousel/carousel.interface.ts
packages/components/carousel/index.ts

Add carousel component
Support mouse scroll; touchpad wheel; next, prev, show more buttons; adaptive to screen

feat(carousel): add carousel component

---

package.json
packages/components/carousel/carousel.component.ts
packages/components/carousel/carousel.interface.ts

fix(carousel): make buttons optional

---

package.json
packages/components/date/xm-datetime-control.ts

Optional time field
Handle label click

fix(date-time-control): optional time, handle label click

---

package.json
packages/components/link/xm-link.ts

link add param to open link at new tab

fix(core): add param to open link in new tab

---

package.json
packages/administration/specification-management/uaa-login-mng/uaa-login-mng.component.spec.ts
packages/components/ng-package.json
packages/components/package.json
packages/components/register/register.component.html
packages/components/register/register.component.ts
packages/shared/src/shared.module.ts

feat(register): update RecaptchaModule

---

package.json
packages/components/date/xm-date-range-control.ts
packages/components/layout/form/form-layout.component.ts
packages/components/layout/form/form-layout.model.ts

Add default value, disable, validators
Fix initial button state
Code improve

fix(layout-form): default value, disabled; fix initial state

---

package.json
packages/entity/src/entity-list-card/entity-list/entity-list.component.html
packages/entity/src/function-list-section-compact/function-list-section-compact.component.html

For deeper styling state ability

feat: states colors class

---

package.json
packages/dashboard/src/components/dashboard/dashboard.component.html
packages/dashboard/src/components/dashboard/dashboard.component.ts
packages/dashboard/src/xm-dashboard.module.ts
packages/dynamic/widget/xm-dynamic-widget.directive.ts

Now we could specify controllers in dashboard configuration in the same way as it works with widgets or layout

feat(dashboard-controllers): inject services by dashboard config

---

package.json
packages/components/edit-buttons/edit-widget-buttons.component.html
packages/components/edit-buttons/edit-widget-buttons.component.ts
packages/components/edit-buttons/edit-widget-buttons.model.ts
packages/components/edit-buttons/edit-widget-buttons.module.ts

added permission directive for buttons

feat(edit-widget-buttons): added permission

---

package.json
packages/components/autocomplete-control/autocomplete-chips-control.component.stories.ts
packages/components/autocomplete-control/autocomplete-table-control.component.stories.ts
packages/components/form-layout/xm-form-layout.stories.ts
packages/components/inline-control/xm-inline-layout.stories.ts
packages/components/navbar-user-widget/navbar-user-widget.stories.ts
packages/components/table/table-widget/xm-table-widget.stories.ts
packages/components/text/text-dynamic-view/xm-text-dynamic-view.stories.ts
packages/dynamic/src/loader/xm-dynamic-component-registry.spec.ts

fix(dynamic): fix tests

---

package.json
packages/components/table/animations/xm-table-widget.animation.ts
packages/components/table/components/xm-table-expand-panel-button.component.ts
packages/components/table/components/xm-table-header.component.ts
packages/components/table/directives/xm-table.model.ts
packages/components/table/table-widget/xm-table-widget.component.html
packages/components/table/table-widget/xm-table-widget.component.scss
packages/components/table/table-widget/xm-table-widget.component.ts

add posibility via config make expand\collapse panel in table

feat(xm-table): add expand panel

---

package.json
packages/components/table/components/xm-table-filter-inline.component.ts

fix(xm-table-filter-inline): fix on empty filters

---

packages/components/table/components/xm-table-filter-chips.component.ts
packages/components/table/components/xm-table-filter-inline.component.ts

add filterExpand fot toggle filter

feat(xm-table-filter-inline): add filterExpand to filter

---

package.json
packages/components/layout/form/form-layout.component.html

fix(layout-form): add form value to condition

---

package.json
packages/components/text/text-dynamic-view/xm-text-dynamic-view.ts

feat(dynamic-view): handle empty value

---

package.json
packages/pipes/src/xm-emtpy.pipe.ts

isEmpty function considering number as empty, fix

fix(is-empty): check is empty (include number)

---

package.json
packages/entity/card/xm-mat-card.component.html

fix(xm-mat-card): add overflow-hidden

---

package.json
packages/components/table/directives/xm-table-mat-sort-adapter.directive.ts
packages/components/table/directives/xm-table.directive.ts
packages/components/table/table-widget/xm-table-widget.component.html

fix(xm-table-widget): table sort

---

package.json
packages/components/table/components/xm-table-filter-chips.component.ts

set value to filter title for mapping and correct view value in chips

fix(filter-chips): set value to filter title

---

package.json
src/i18n/uk/core.json

Extended translation to Ukrainian

Added missed branches and updated UK translations: core.json

---

package.json
packages/components/layout/data/data-layout.model.ts
packages/controllers/features/resource-array-data/resource-array-data.service.ts

make ResourceArrayDataService ruesable

feat: move key to config, get controller by key, change model

---

package.json
packages/alert/_alert.scss
packages/components/table/components/xm-table-filter-inline.component.ts

fix styles in table-filter-inline, add border-radius to mat-dialog

fix(xm-table-filter-inline): fix styles, add border-radius to mat-dialog

---

package.json
packages/administration/audits/audits.component.ts
packages/components/table/controllers/elastic/xm-table-filter-elastic.ts
packages/components/text/text-join/xm-text-join.component.ts
packages/core/entity/event.service.ts
packages/core/user/src/principal.service.ts
packages/entity/src/calendar-card/calendar-view/calendar-view.component.ts
packages/entity/src/calendar-event-dialog/calendar-event-dialog.component.ts
packages/json-schema-form/components/date-picker/date-picker.component.ts
packages/json-schema-form/components/datetime-picker/datetime-picker.component.ts
packages/json-schema-form/components/datetime-utc/datetime-utc.component.ts
packages/operators/index.ts
packages/operators/src/dayjs-util.ts
packages/translation/pipes/xm-date-time.pipe.ts
packages/translation/src/services/language.service.ts

feat(dayjs): change moment with dayjs

---

package.json
packages/operators/src/dayjs-util.ts

fix(dayjs): fix build

---

package.json
packages/core/entity/event.service.ts
packages/entity/src/calendar-card/calendar-view/calendar-view.component.ts
packages/json-schema-form/components/date-picker/date-picker.component.ts
packages/json-schema-form/components/datetime-utc/datetime-utc.component.ts
packages/operators/package.json
packages/operators/src/dayjs-util.ts
packages/translation/pipes/xm-date-time.pipe.ts
packages/translation/src/services/language.service.ts

fix(dayjs): fix build dayjs.tz

---

package.json
packages/translation/src/services/language.service.ts

fix(language.service): remove unused import

---

package.json
packages/components/layout/card/card-layout.component.html
packages/components/layout/card/card-layout.model.ts
packages/components/layout/expandable/expandable-layout.component.html
packages/components/layout/expandable/expandable-layout.model.ts

add data-qa attributes to the layout widgets

feat(layout): add data-qa attributes to the layout widgets

---

package.json
packages/timeline/timeline-list/timeline-list.component.ts

fix load all timeline items for version two

fix(timeline-list): load all timeline items for version two

---

package.json
packages/alert/src/xm-alert.stories.ts
packages/components/autocomplete-control/autocomplete-chips-control.component.stories.ts
packages/components/autocomplete-control/autocomplete-control.component.stories.ts
packages/components/autocomplete-control/autocomplete-table-control.component.stories.ts

fix(storybook-injection-service): add injectable service

---

packages/components/date-range/xm-date-range.component.ts
packages/translation/pipes/xm-date.pipe.ts

fix date locale on change account settings

fix(xm-date-range): fix date locale on change acc settings

---

package.json
packages/components/autocomplete-control/autocomplete-control.ts
packages/components/text/text-dynamic-view/xm-text-dynamic-view.ts

Autocomplete control lodash import
Text dynamic view check number

Autocomplete control and Text dynamic view refactoring

---

package.json
src/app/xm.module.ts

fix(core): fix  imports xm-module translations

---

package.json
packages/administration/translations/services/translation-config.service.ts
packages/translation/src/xm-translation.module.ts
src/app/xm.module.ts

add public config translationsFromMsConfig 
to swich feature with translation from ms config

fix(core): add public config translationsFromMsConfig 

---

package.json
packages/components/enum/value/xm-enum.component.ts

add insert dynamic component to the enum

feat(xm-enum): add dynamic component

---

package.json
packages/components/table/components/xm-table-filter-chips.component.ts

fix displaying chips items
now the width of the container with chips is calculated taking margins

fix(xm-table-filter-chips): displaying chips items

---

package.json
packages/components/inline-control/inline-control.component.ts
packages/components/table/components/xm-table-filter-chips.component.ts

fix(xm-table-filter-chips): disabled chips fixed

---

package.json
packages/components/login/login.service.ts
src/app/layouts/components/layout-wrapper/layout-wrapper.component.ts

- hide sidebar after user logout to hide unnecessary margin space reserving

Fix: Sidebar close after logout

---

package.json
packages/components/menu/menu.component.ts
packages/components/menu/menu.service.ts
src/app/layouts/components/layout-wrapper/layout-wrapper.component.html
src/app/layouts/components/layout-wrapper/layout-wrapper.component.ts

- disable sidenav animation when it's not M3 Menu and not a mobile view

feature: Disable sidenav animation

---

package.json
packages/core/auth/src/xm-auth-target-url.service.ts
packages/core/user/src/principal.service.ts
packages/dashboard/home/home.component.ts

Redirect user to previous url once logged in.

fix(redirect-url): navigate once

---

packages/core/auth/src/xm-auth-target-url.service.ts
packages/core/user/src/principal.service.ts
packages/dashboard/home/home.component.ts

Previously we forgot to separate query params from redirect url

Parse query params from redirect url

---

package.json
packages/components/table/components/xm-table-filter-inline.component.ts

feat(xm-table-filter-inline): prevent 2 request on init

---

package.json
packages/components/menu/menu-categories/_menu-categories-theme.scss
packages/components/menu/menu-categories/menu-categories.component.html
packages/components/menu/menu-categories/menu-categories.component.ts
packages/components/menu/menu.animation.ts
packages/components/menu/menu.component.ts
packages/components/sidebar/sidebar.component.ts

- fix bug when sidenav in over mode and same category does not open on hover event
- add color to the toggle button (open/close sidenav)
- fix animation failed execution
- add support for the base64 icons for the brand logo in menu-categories.component

fix: M3 menu improvements (hover, styles, animation, brand logo)

---

package.json
packages/components/key-filter/index.ts
packages/components/key-filter/key-filter.component.ts
packages/components/key-filter/ng-package.json
packages/components/module/xm-array.registry.ts
packages/operators/index.ts
packages/operators/src/get-value.ts
packages/operators/src/key-predicate.spec.ts
packages/operators/src/key-predicate.ts

Search value from nested arrays

feat(key-filter): search from nested arrays

---

package.json
packages/components/menu/menu-categories/_menu-categories-theme.scss

- make the style of the categories the same as menu.component

feat: Change default styles for the categories

---

package.json
packages/controllers/features/edit-state-store/edit-state-store.service.ts

fix revert broken changes view state on create

fix(core): fix revert broken changes view state on create

---

package.json
packages/components/menu/menu.mdx
packages/components/menu/menu.service.ts
packages/components/menu/menu.stories.ts
packages/components/text/text-dynamic-view/xm-text-dynamic-view.stories.ts

docs: Storybook for the sidenav (M3 menu)

---

packages/components/validator-processing/validator-processing.service.ts

Now we could add offset in milliseconds to compare date

fix(validators): ability to add offset to dateMoreThanIn validator

---

package.json
packages/components/date/index.ts
packages/components/date/shared/parse-time.ts
packages/components/date/xm-datetime-control.ts

feat(datetime): parse optional seconds

---

package.json
packages/components/layout/form/form-layout.component.ts

fix(form-layou.component): fix reset state

---

package.json
packages/components/link/index.ts
packages/components/link/link-with-subtext/xm-link-with-subtext.component.html
packages/components/link/link-with-subtext/xm-link-with-subtext.component.ts
packages/components/link/link-with-subtext/xm-link-with-subtext.stories.ts
packages/components/link/xm-link.model.ts
packages/components/module/xm-link.registry.ts

feat: Link with subtext value

---

package.json
packages/components/date/xm-date-control.ts

fix(xm-date-control): invalid import path fixed

---

package.json
packages/components/text/text-range-control/xm-text-range-control.component.ts

feat(xm-text-range-control): added default count value

---

package.json
packages/components/menu/menu-categories/_menu-categories-theme.scss
packages/components/menu/menu-categories/menu-categories.component.html
packages/components/menu/menu-categories/menu-categories.component.ts
packages/components/menu/menu.service.ts

- changed menu behaviour when user wants to open or close it manually (by button fold/unfold)

feat: M3 menu pin/unpin

---

package.json
packages/components/enum/control/xm-enum-control.component.ts

reset value when component destroy fixed

fix(enum-control): reset value when component destroy fixed

---

package.json
packages/components/link/xm-link.ts

For the cases when you need to change default QueryParamsHandling. See official docs for possible values: https://next.angular.dev/api/router/QueryParamsHandling

feat: Add QueryParamsHandling to the xm-link

---

package.json
packages/components/layout/data/data-layout.component.ts

Fixed behaviour when data-layout.component send two API calls instead of one.

fix: data-layout.component duplicated api calls

---

src/styles/_menu-m3.scss
src/styles/_theme.scss

Apply styles according to M3 style guide:
https://m3.material.io/components/menus/specs

feat(mat-menu-style): apply M3 styles

---

package.json
packages/components/link/index.ts
packages/components/link/xm-external-link-button/xm-external-link-button.component.html
packages/components/link/xm-external-link-button/xm-external-link-button.component.ts
packages/components/link/xm-external-link-button/xm-external-link-button.model.ts
packages/components/link/xm-external-link-button/xm-external-link-button.stories.ts
packages/components/module/xm-link.registry.ts

- add component with the button that can open an external link
- add stories for the Storybook (for the Compodoc format)
Example:

Feat: External link button

---

package.json
packages/components/table/components/xm-quick-filters-control.component.ts

fix if this.formGroup without contols

fix(core): quick-filters fix if no form controls

---

packages/components/table/controllers/config/xm-table-columns-setting-storage.service.ts
packages/core/permission/src/xm-permission.service.ts

check permissions hasPrivilegesBy  change to array

fix(core): fix find permissions

---

package.json
packages/styles/src/_material-mat-dialog.scss

fix(material-mat-dialog.scss): fixed mat dialog border radius

---

package.json
packages/components/form-layout/xm-form-layout.component.ts

add posibility to hide field by restrictions

fix(core): add posibility to hide field by Permission

---

package.json
packages/components/table/cells/show-hide-columns-settings/show-hide-columns-settings.component.html
packages/components/table/cells/show-hide-columns-settings/show-hide-columns-settings.component.ts
packages/components/table/controllers/config/xm-table-columns-setting-storage.service.ts
packages/components/table/directives/xm-table.directive.ts

In order to avoid empty table we need to ignore column with property "storageColumn"

feat(storage-column): do not hide storageColumn

---

package.json
packages/components/table/table-widget/xm-table-widget.component.html
packages/components/table/table-widget/xm-table-widget.component.ts

reference: https://github.com/angular/components/issues/15885

fix(sticky-overlaps): recalculate sticky styles

---

package.json
packages/components/menu/_menu-theme.scss
packages/components/menu/menu-categories/_menu-categories-theme.scss
packages/components/sidebar/sidebar.component.scss
packages/components/sidebar/xm-sidebar-state.component.scss
src/app/layouts/components/layout-wrapper/layout-wrapper.component.html
src/app/layouts/components/layout-wrapper/layout-wrapper.component.scss
src/app/layouts/components/top-panel/top-panel.animation.ts
src/app/layouts/components/top-panel/top-panel.component.html
src/app/layouts/components/top-panel/top-panel.component.scss
src/app/layouts/components/top-panel/top-panel.component.ts
src/app/layouts/components/top-panel/top-panel.model.ts
src/app/layouts/layout.module.ts
src/app/layouts/main.component.html
src/app/layouts/main.component.scss

This component is responsible for rendering the snackbar widget or top panel layout that collapses the main content on its height.
To make it works you need to provide the public UI configuration in format (example below):
```yaml
topPanel:
position: 'on-top' // mandatory, possible values: 'on-top' or 'before-dashboard-content'. This option is used in `src/app/layouts/main.component.html` and defines position where to display component.
snackbar: // optional
selector: 'your/component/selector'
config: // use MatSnackBarConfig
panelClass: 'your-class-with-custom-styles' // in case you want to add custom styles to the snackbar. Should be defined in the global styles or in component with `encapsulation: ViewEncapsulation.None`
verticalPosition: 'top' // The vertical position to place the …
```

Feat: Top panel

---

package.json
packages/components/table/animations/xm-table-widget.animation.ts
packages/components/table/components/export-button/xm-table-export-buttons.model.ts
packages/components/table/components/selection-header/xm-table-selection-header.component.scss
packages/components/table/components/selection-header/xm-table-selection-header.component.ts
packages/components/table/components/selection-header/xm-table-selection.model.ts
packages/components/table/components/xm-table-selection-column.component.ts
packages/components/table/directives/xm-table.model.ts
packages/components/table/table-widget/xm-table-widget.component.html
packages/components/table/table-widget/xm-table-widget.config.ts
packages/components/table/table-widget/xm-table-widget.stories.ts

move selection panel to table config, add layout with actions, dinamyc service, small redesigne, refactor

feat(selection-panel): rework selection panel

---

package.json
packages/components/language-menu/xm-navbar-language-menu-widget.component.ts

If the input showAlways is not provided, the component's behavior remains the same as before.
If the input showAlways is provided, it allows changing the language even if the user is authenticated.

Add Conditional Visibility for Navbar Language Menu Widget

---

package.json
packages/components/letter-control/letter-control.ts

- Updated a letter control to have an optional placeholder; 
- Updated a letter control to handle raw string array values.

Updated a letter control to have a placeholder and a raw array values event

---

package.json
packages/common-webapp-ext/sign-in-up-v2-widget/login-v2/login-v2.component.html
packages/common-webapp-ext/sign-in-up-v2-widget/login-v2/login-v2.component.scss
packages/common-webapp-ext/sign-in-up-v2-widget/login-v2/login-v2.component.ts
packages/common-webapp-ext/sign-in-up-v2-widget/sign-in-marketing/sign-in-marketing.component.scss
packages/common-webapp-ext/sign-in-up-v2-widget/sign-in-up-v2-widget.component.html
packages/common-webapp-ext/sign-in-up-v2-widget/sign-in-up-v2-widget.component.scss
packages/common-webapp-ext/sign-in-up-v2-widget/sign-in-up-v2.model.ts
packages/components/language-menu/xm-navbar-language-menu-widget.component.ts

- add header with logo, title and description
- adjust tablet adaptation for the sign-in-marketing widget
- add possibility to hide language selector on sign-in page

Feat: Add header to the sign-in card:

---

package.json
packages/components/buttons/components/button-base.ts
packages/components/buttons/components/fab-button/fab-button.component.html
packages/components/buttons/components/fab-button/fab-button.component.ts
packages/components/buttons/components/fab-mini-button/fab-mini-button.component.html
packages/components/buttons/components/fab-mini-button/fab-mini-button.component.ts
packages/components/buttons/controllers/button-controller-base.ts
packages/components/buttons/index.ts
packages/components/buttons/ng-package.json
packages/components/buttons/styles/button-general.scss
packages/components/buttons/types/button-config.interface.ts
packages/components/buttons/types/button-controller-base.interface.ts
packages/components/buttons/types/fab-button-config.interface.ts
packages/components/module/xm-buttons.registry.ts
packages/components/module/xm-ngx-components.module.ts

Fab buttons with controller support

feat(fab-button): Add fab-buttons feature

---

package.json
packages/components/enum/value/xm-enum.component.ts

fix display title if item is object

fix(xm-enum): display title fixed

---

package.json
packages/components/logo/image-logo/image-logo.component.spec.ts
packages/components/menu/menu-categories/menu-categories.component.spec.ts
src/app/layouts/main.component.spec.ts

Fix karma tests broken by menu refactoring.

FIX: karma tets after menu migration

---

package.json
packages/components/table/directives/xm-table.directive.ts
packages/components/table/table-widget/xm-table-widget.component.html

To make your tables load data with skeleton loader add this config to your public UI config:
```yaml
// ...other params
skeleton:
table:
isSkeletonLoading: true
```

feat: Set skeleton loading for tables from public UI config

---

package.json
packages/components/date/xm-date-control.ts

Hide clear button ```X``` when necessary.

feat(xm-date-control): hide clear button when necessary

---

package.json
packages/components/date/xm-date-range-control.ts

Add ability to configure max range between from and to dates

feat(date-range-control): Add maxRangeInDays configuration

---

package.json
packages/components/table/repositories/xm-entity-repository.service.ts

These changes need for ability to pass headers from subclass in query method

Add headers query parameter to query method in entity repository service
